---
- name: setup all nodes
  hosts: all
  tasks:

  - name: update all packages
    yum:
      name: '*'
      state: latest
    become: yes

  - name: install network tools
    yum:
      name: net-tools
    become: yes

  - name: Make k8s repo
    blockinfile:
      path: /etc/yum.repos.d/kubernetes.repo
      create: yes
      block: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

# Install required packages.
  - name: install kubestuff
    yum:
      name:
        - epel-release
        - vim
        - git
        - curl
        - wget
        - kubelet
        - kubeadm
        - kubectl
    become: yes

# Disable SEL
  - name: Put SELinux in permissive mode, logging actions that would be blocked.
    selinux:
      policy: targeted
      state: permissive

# Turn off swap.
  - name: Turn off swap 
    replace:
      path: /etc/fstab
      regexp: '^/dev/mapper/centos-swap\s*swap\s*swap\s*defaults\s*[0-9]\s*[0-9]$'
      replace: '# /dev/mapper/centos-swap swap                    swap    defaults        0 0'
    become: yes

  - modprobe:
      name: overlay
      state: present

  - modprobe:
      name: br_netfilter
      state: present

  - name: add k8s networking conf files
    blockinfile:
      create: yes
      path: /etc/sysctl.d/kubernetes.conf
      block: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward = 1
      

# Install required packages.
  - name: install prereqs 
    yum:
      name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    become: yes

  - name: Add docker repository
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo

# Install required packages.
  - name: install docker stuff
    yum:
      name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
    become: yes

  - name: Create settings directories
    file:
      path: 
      - /etc/docker
      - /etc/systemd/system/docker.service.d
      state: directory

  - name: Create daemon json config file
    blockinfile:
     create: yes
     path: /etc/docker/daemon.json
     marker: ""
     block: |
       {
         "exec-opts": ["native.cgroupdriver=systemd"],
         "log-driver": "json-file",
         "log-opts": {
           "max-size": "100m"
         },
         "storage-driver": "overlay2",
         "storage-opts": [
           "overlay2.override_kernel_check=true"
         ]
       }
  - name: restart service docker, also issue daemon-reload to pick up config changes
    systemd:
      state: restarted
      daemon_reload: yes
      name: docker

  - name: enable docker
    systemd:
      name: docker
      state: started
      enabled: True

- name: setup worker node
  hosts: worker
  tasks:

  - name: opening tcp firewall ports
    firewalld:
      port: "{{ item }}" 
      permanent: yes
      state: enabled
    loop:
      - 10250/tcp
      - 30000-32767/tcp
      - 5473/tcp
      - 179/tcp 
      - 5473/tcp
      - 4789/udp
      - 8285/udp
      - 8472/udp

- name: setup master node
  hosts: master
  tasks:

  - name: opening tcp firewall ports
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
    loop: 
      - 6443/tcp
      - 2379-2380/tcp
      - 10250/tcp
      - 10251/tcp
      - 10252/tcp
      - 5473/tcp
      - 179/tcp
      - 5473/tcp
      - 4789/udp
      - 8285/udp
      - 8472/udp

  - name: enable kubelet
    systemd:
      name: kubelet
      state: started
      enabled: True

  - name: pulling container images with kubeadm
    command: kubeadm config images pull
